### ISSUE TITLE
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word

### ISSUE THREAD

**Issue by NSMNIA** [Aksem/libavoid-js#11]
I encountered a runtime error while using the library, which seems related to WebAssembly instantiation. Below is the detailed error message:

```
RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0)
    at S (libavoid.js:27:17)
    at libavoid.js:32:37
```

Steps to Reproduce:

1. Overwrite the dist folder of version 0.3.1 with the dist folder from version 0.4.0.
2. Update the library path from `lib/libavoid-js-0.3.1/dist/index.mjs` to `lib/libavoid-js-0.4.0/dist/index-node.mjs`.

I also tried rebuilding the dist output, but the issue persists.

Environment:

- Library Version: 0.4.0
- Browser: Arc Version 1.44.2 (50412)
- OS: macOs Sonoma 14.5 (23F79)
- Node: v20.13.1
- Stack: Vite + React

Thank you for your assistance!

**Comment by Aksem** [comment]
Hi @NSMNIA ,

This error means, that libavoid.wasm file is invalid. Could you please check in Network tab of the browser, that it is downloaded without errors and its size(in original v0.4.0 build) is ~473.9 KiB?

**Comment by trufak** [comment]
@NSMNIA, please describe in more detail where you need to move the libavoid.wasm file so that there is no error.

**Comment by Aksem** [comment]
@trufak , it depends on your project setup. libavoid.wasm should be available in root: <address>/libavoid.wasm . It is easier to give better advice with details about your project setup(framework, build tool, etc.) and deployment environment. If your project is not open-source, please provide more details or create a simple example app.

**Comment by trufak** [comment]
my frameworks are react and electron.
Therefore, I thought that moving the file to the public folder should have worked, but no...

**Comment by Aksem** [comment]
Thanks for the example, it helped a lot!

The problem was that libavoid-js tried to load `libavoid.wasm` from js directory: in Network tab it was `http://localhost:3000/static/js/libavoid.wasm`. The easiest solution is to provide explicit path to wasm file in call of `load` function: 
`await AvoidLib.load('/libavoid.wasm');` in `src/avoid-router.js:9`

Now it works:)

**Comment by trufak** [comment]
Yes, it works!
Thanks!
